-- =============================================================================
-- DPIRD Digital Advisory Platform - Full Prototype Seed Data from Excel
-- Target Database: Supabase (PostgreSQL 15+)
-- File: 04_seed_data.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Sectors
-- -----------------------------------------------------------------------------
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('7fdb0313-5f95-4c2d-b361-cae6cc9dc64e', 'Agriculture', 'agriculture', NULL, 'agriculture', 'Primary agricultural production including livestock, crops and land management.', true, 1) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('23a46d98-921f-4803-9ffd-5e490145e65b', 'Food & Beverage', 'food_beverage', NULL, 'restaurant', 'Food and beverage manufacturing, processing and distribution.', true, 2) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('839e2e9d-2e32-47b0-b355-63058a86e12a', 'Food Manufacturing', 'food_manufacturing', '23a46d98-921f-4803-9ffd-5e490145e65b', 'factory', 'Industrial-scale food manufacturing and processing operations.', true, 3) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('dbe5a554-4d3e-49a8-80d2-b711c66a1a8c', 'Aquaculture', 'aquaculture', '7fdb0313-5f95-4c2d-b361-cae6cc9dc64e', 'water', 'Aquaculture and marine farming operations in Western Australia.', true, 4) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('32b9a7fb-6042-428b-b761-415b709e0ea0', 'Horticulture', 'horticulture', '7fdb0313-5f95-4c2d-b361-cae6cc9dc64e', 'local_florist', 'Fruit, vegetable and flower growing operations.', true, 5) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('9d872682-6a6d-414d-914c-ef0cd70fd454', 'Retail & Wholesale', 'retail', NULL, 'storefront', 'Retail trade, wholesale distribution and consumer goods.', true, 6) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('8a3b25d5-2063-445b-800b-a78d0b6c1456', 'Construction & Trade', 'construction', NULL, 'construction', 'Building, construction, civil engineering and trade services.', true, 7) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('2b82a710-2246-4be5-84cf-6f8f4b7f0bd0', 'Professional Services', 'professional_services', NULL, 'business_center', 'Legal, accounting, consulting and professional advisory services.', true, 8) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('ff076e36-76b2-4480-98a8-8d394352c79b', 'Regional Development', 'regional_development', NULL, 'location_city', 'Regional and rural business development across Western Australia.', true, 9) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('9dc6c815-0ee4-4bf0-83f4-1ac0e7d0e963', 'Indigenous Business', 'indigenous_business', NULL, 'groups', 'Aboriginal and Torres Strait Islander owned and operated businesses.', true, 10) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('848ae804-a8e2-4ea0-97cd-b478b18c1b12', 'Environmental & Sustainability', 'environmental', NULL, 'eco', 'Environmental management, conservation and sustainability programs.', true, 11) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('07f3c3b7-8274-474a-9d03-67879f9eca21', 'Fishing & Recreation', 'fishing_recreation', NULL, 'phishing', 'Recreational fishing and related marine activities.', true, 12) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO sectors (id, name, slug, parent_id, icon, description, is_active, sort_order) VALUES ('c3e7c9b3-79d9-4db9-8adb-e78492bcf6e5', 'Creative Industries', 'creative_industries', NULL, 'palette', 'Film, media, arts and cultural creative industries.', true, 13) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- -----------------------------------------------------------------------------
-- 2. Tags
-- -----------------------------------------------------------------------------
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('375150a6-354f-4672-83cb-d889fb981aeb', 'website', 'Sitio web', 'digital', 'El negocio tiene o necesita un sitio web', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('ba262b11-718f-41fd-8a7e-5f796477e6b7', 'ecommerce', 'E-commerce', 'digital', 'Venta online activa o necesidad de implementarla', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('8d332fb9-c25c-4c13-8f81-609a33c274ec', 'social_media', 'Redes sociales', 'digital', 'Presencia o necesidad de gestión de redes sociales', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('32a1dbd9-19a8-4b56-abb5-2b7201c23053', 'crm', 'CRM / Gestión clientes', 'digital', 'Sistema de gestión de relaciones con clientes', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('d070ad54-d55c-4e47-959a-74159a5817f1', 'inventory_software', 'Software de inventario', 'digital', 'Gestión digital de stock e inventario', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('ab9e2ddc-2f73-423e-a651-877c2543875d', 'pos_system', 'Sistema POS', 'digital', 'Punto de venta digital (hardware/software)', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('7174489a-95cd-4591-ba90-f957b1704e96', 'cybersecurity', 'Ciberseguridad', 'digital', 'Necesidad de protección de datos y seguridad informática', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('7a786869-8c9e-46c0-95c0-9b15a11f916f', 'ai_tools', 'Herramientas de IA', 'digital', 'Uso o adopción de inteligencia artificial en operaciones', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('fced5da6-dc31-4fc8-ae0a-f7c9f463f706', 'cloud_services', 'Servicios en la nube', 'digital', 'Uso de plataformas cloud (AWS, Google Cloud, Microsoft 365)', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('29e51eb9-cfa7-4423-8065-8524793cb86b', 'digital_marketing', 'Marketing digital', 'digital', 'SEO, SEM, email marketing y campañas digitales', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('e18287c0-ec33-4c81-a543-e173225a3ea7', 'online_booking', 'Reservas online', 'digital', 'Sistema de reservas o turnos digitales', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('1ac2648a-6cef-4e29-80a2-998d12e065f3', 'business_software', 'Software de gestión', 'digital', 'ERP, contabilidad digital, software de operaciones', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('196269bd-7311-4b52-8a00-21dd76e7c128', 'no_digital_presence', 'Sin presencia digital', 'digital', 'Negocio sin ninguna herramienta o presencia digital', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('e03bc7a4-c40d-486e-b653-957000cc06d5', 'supply_chain', 'Cadena de suministro', 'operations', 'Gestión y optimización de cadena de suministro', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('4df73018-979d-4147-99c5-7ee04d9ec55c', 'quality_control', 'Control de calidad', 'operations', 'Procesos de control y aseguramiento de calidad', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('81892e18-cc47-4037-a05d-744e13b40cba', 'compliance', 'Cumplimiento normativo', 'operations', 'Adherencia a regulaciones y normativas sectoriales', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('6a7b1107-e612-4104-b14e-a6361c7f97ab', 'certification', 'Certificaciones', 'operations', 'Obtención o mantenimiento de certificaciones (orgánico, ISO, etc.)', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('be2bb8ba-ea21-477f-8ced-085452bdaf08', 'process_automation', 'Automatización de procesos', 'operations', 'Digitalización y automatización de procesos manuales', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('056cada1-55e0-44fa-a5f8-133d06d03203', 'water_management', 'Gestión del agua', 'operations', 'Eficiencia hídrica y manejo de recursos de agua', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('9bb0dc5e-1743-46ce-87d9-39a593298b38', 'biosecurity', 'Bioseguridad', 'operations', 'Control de plagas, enfermedades y gestión de bioseguridad', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('b22d8e9d-e785-496c-95d2-65a81934719c', 'carbon_farming', 'Carbon farming', 'operations', 'Secuestro de carbono y prácticas de agricultura de carbono', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('5967a623-bf35-48e8-9973-e6a5a50fcc5d', 'logistics', 'Logística y distribución', 'operations', 'Transporte, distribución y logística de productos', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('69a36261-3837-4864-88d5-8b9a052d34ea', 'food_safety', 'Seguridad alimentaria', 'operations', 'Cumplimiento de normativas de inocuidad alimentaria', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('485ca52f-aa46-4225-b55d-220c7ec6fe55', 'export', 'Exportación', 'market', 'Venta de productos o servicios en mercados internacionales', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('f2c0a3d5-7598-4e0b-b636-3d03397bfa0e', 'import', 'Importación', 'market', 'Importación de insumos o productos del exterior', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('eeca24b1-1f45-488c-a644-01779acf7ee3', 'b2b_sales', 'Ventas B2B', 'market', 'Ventas entre empresas (business-to-business)', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('2a8324bf-d7d5-459a-9e86-97047eda7821', 'digital_marketing_mkt', 'Estrategia de mercado digital', 'market', 'Estrategia de adquisición y retención de clientes online', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('f8b8bce4-107d-4c77-bf13-e6d1cdeb4067', 'brand_development', 'Desarrollo de marca', 'market', 'Construcción y posicionamiento de marca', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('cde69925-71af-452f-b325-7faca1ee2259', 'indigenous_market', 'Mercado indígena', 'market', 'Foco en mercados o comunidades indígenas', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('d1621af5-6e9b-4439-96e3-808fb0ef4d3b', 'regional_market', 'Mercado regional WA', 'market', 'Foco en mercados regionales de Western Australia', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('ee5cb1d8-501a-4e73-bdf4-60698f8c059e', 'international_trade', 'Comercio internacional', 'market', 'Operaciones de comercio exterior (import + export)', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('eeb81853-523e-4059-af72-593c0ebbae8b', 'abn_required', 'ABN requerido', 'eligibility', 'El programa requiere Australian Business Number activo', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('ca3a1a87-07b7-4341-a46d-4029f08dc362', 'gst_registered', 'GST registrado', 'eligibility', 'El programa requiere registro en GST', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('d73a91f0-4e47-4718-a4e7-2b9c754825c7', 'indigenous_business_elig', 'Negocio indígena', 'eligibility', 'Condición de negocio Aboriginal/Torres Strait Islander', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('7fbab832-6e72-494b-9a3a-2904bf7b6b04', 'financially_solvent', 'Solvencia financiera', 'eligibility', 'El programa requiere demostrar solvencia financiera', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('cb9f8a4d-8977-48c7-bd41-b6dc5516c96a', 'international_supply_chain', 'Supply chain internacional', 'eligibility', 'Mínimo 2 años operando en cadena de suministro internacional', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('b7286565-75fc-424f-a034-052c82669da8', 'water_license', 'Licencia de agua', 'eligibility', 'Requiere licencia activa de agua (WA)', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('fd24f5d3-0918-4a7e-bbc6-7f02fa1240df', 'matching_funding', 'Co-financiamiento requerido', 'eligibility', 'El programa requiere un porcentaje de co-financiamiento del aplicante', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('6ca109ea-c861-482d-a8a5-74b00f8581df', 'primary_producer', 'Productor primario', 'eligibility', 'El aplicante debe ser productor primario', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('cb572c93-127f-4724-9e68-d83ce75c6ee7', 'community_org', 'Organización comunitaria', 'eligibility', 'El aplicante debe ser una organización comunitaria reconocida', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('1dd94cf4-6aa7-4d8d-b5b8-34b97cc8904b', 'foundational', 'Nivel Fundacional (DML 0-24)', 'dml', 'Negocios sin herramientas digitales básicas', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('8229a90b-1908-43ab-b655-2d9bbf498f88', 'emerging', 'Nivel Emergente (DML 25-49)', 'dml', 'Negocios con primeras herramientas digitales, uso inconsistente', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('ad6b73d2-c447-42ff-8124-69b4bb3fe250', 'established', 'Nivel Establecido (DML 50-74)', 'dml', 'Digital integrado en operaciones clave', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO tags (id, name, label, category, description, is_active) VALUES ('42e87735-2b9a-41d2-9170-7cf81e2f52ec', 'advanced', 'Nivel Avanzado (DML 75-100)', 'dml', 'Digital como ventaja competitiva, datos y automatización', true) ON CONFLICT (id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 3. Grants
-- -----------------------------------------------------------------------------
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('6c97d8b8-9aa6-4f91-aba6-2211bed878d7', 'Community Stewardship Grants', 'community-stewardship-grants', 'DPIRD', 'https://www.dpird.wa.gov.au/community-stewardship-guidelines', 'Supports community-based organisations to undertake stewardship of natural resources in Western Australia.', 'Funding for community-based natural resource stewardship projects in WA.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2026-03-12', '2026-04-29', false, 'single_window', NULL, NULL, NULL, '25% matching funding required', true, ARRAY['company', 'nfp', 'partnership'], 0, NULL, 0, true, false, ARRAY['regional_wa', 'all_wa'], 'inclusive', ARRAY['agriculture', 'environmental', 'regional_development'], ARRAY['supply_chain', 'compliance'], 0, 100, ARRAY['foundational', 'emerging', 'established', 'advanced'], ARRAY['community_org', 'matching_funding'], 0.4, 0.2, 0.4, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('6a05fc97-6311-4780-a70f-cb8105c837c1', 'Feral Cat Management Grants', 'feral-cat-management-grants', 'DPIRD', 'https://www.dpird.wa.gov.au/feral-cat-management-guidelines', 'Funding for local governments and biosecurity groups to manage feral cats in alignment with the WA Feral Cat Strategy.', 'Grants to manage feral cat populations for registered biosecurity groups and local governments.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2026-03-12', '2026-04-29', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'nfp'], 0, NULL, 0, true, false, ARRAY['regional_wa', 'all_wa'], 'inclusive', ARRAY['agriculture', 'environmental'], ARRAY['biosecurity', 'compliance'], 0, 100, ARRAY['foundational', 'emerging', 'established', 'advanced'], ARRAY['biosecurity', 'community_org'], 0.5, 0.1, 0.4, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('78441f34-dd90-4725-9a86-865637cbc119', 'WaterSmart Farms Voucher Program', 'watersmart-farms-voucher', 'DPIRD', 'https://www.dpird.wa.gov.au/watersmart-farms-guidelines', 'Vouchers to support primary producers in Gnangara groundwater areas to implement water efficiency measures.', 'Vouchers for water efficiency improvements for licensed primary producers in Gnangara areas.', 'monetary_grant', 'funding', 'non_competitive', 'business', 'closed', '2026-03-07', '2026-05-03', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['sole_trader', 'company', 'partnership'], 0, NULL, 0, true, false, ARRAY['regional_wa'], 'inclusive', ARRAY['agriculture', 'horticulture'], ARRAY['water_management', 'compliance', 'certification'], 0, 74, ARRAY['foundational', 'emerging', 'established'], ARRAY['water_license', 'primary_producer'], 0.5, 0.2, 0.3, 'eligibility_only', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('e1d13b32-aea8-4131-b82e-dcf6e85d67c2', 'Supply Chain Capacity Program', 'supply-chain-capacity-program', 'DPIRD', 'https://www.dpird.wa.gov.au/supply-chain-capacity-guidelines', 'Supports regional food and beverage businesses to increase processing or logistics capacity.', 'Grants to boost processing and logistics capacity for regional food & beverage businesses.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2026-02-27', '2026-04-24', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'sole_trader', 'partnership'], 0, NULL, 0, true, true, ARRAY['regional_wa'], 'inclusive', ARRAY['food_beverage', 'food_manufacturing', 'regional_development'], ARRAY['supply_chain', 'logistics', 'food_safety'], 0, 74, ARRAY['foundational', 'emerging', 'established'], ARRAY['supply_chain', 'logistics', 'gst_registered'], 0.45, 0.25, 0.3, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('02e54618-cc53-4b38-bdd1-3fb4309faff2', 'Noongar Regional Corporations Economic Foundations Grants', 'noongar-economic-foundations-grants', 'DPIRD', 'https://dpird.smartygrants.com.au/NRCEFG2', 'Supports the 6 Noongar Regional Corporations to undertake economic and business development planning and corporate governance training.', 'Economic development grants exclusively for the 6 Noongar Regional Corporations under the South West Native Title Settlement.', 'monetary_grant', 'funding', 'non_competitive', 'business', 'open', '2026-02-16', '2026-06-30', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'nfp'], 0, NULL, 0, true, false, ARRAY['regional_wa'], 'required', ARRAY['indigenous_business', 'regional_development'], ARRAY['brand_development', 'b2b_sales', 'compliance'], 0, 100, ARRAY['foundational', 'emerging', 'established', 'advanced'], ARRAY['indigenous_business_elig', 'community_org'], 0.35, 0.25, 0.4, 'eligibility_only', 'smartygrants', 'enquiries@dpird.wa.gov.au', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('8dc3a80b-b148-4689-b8f7-7052c335e3eb', 'Building Better Aboriginal Business Supply Chain Voucher', 'bbab-supply-chain-voucher', 'DPIRD', 'https://www.dpird.wa.gov.au/bbab-supply-chain-voucher-guidelines', 'Vouchers for Aboriginal-owned businesses operating in primary industry or related supply chains, with at least 12 months trading history.', 'Supply chain vouchers for Aboriginal-owned primary industry businesses with 12+ months trading.', 'monetary_grant', 'funding', 'non_competitive', 'business', 'closed', '2025-12-03', '2026-02-02', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'sole_trader', 'partnership'], 0, NULL, 1, true, false, ARRAY['regional_wa', 'all_wa'], 'exclusive', ARRAY['indigenous_business', 'agriculture', 'regional_development'], ARRAY['supply_chain', 'logistics'], 0, 74, ARRAY['foundational', 'emerging', 'established'], ARRAY['indigenous_business_elig', 'primary_producer'], 0.4, 0.2, 0.4, 'eligibility_only', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('b6262eb8-a868-4f26-abbf-d411f641d22a', 'Value Add Investment Grants — Capital Investment Stream', 'value-add-investment-grants-capital', 'DPIRD', 'https://www.dpird.wa.gov.au/value-add-guidelines', 'Capital investment grants to support value-adding activities in regional WA businesses.', 'Capital grants for value-adding investments in regional WA food and agri businesses.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2024-03-22', '2024-05-03', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'sole_trader'], 0, NULL, 2, true, true, ARRAY['regional_wa'], 'inclusive', ARRAY['food_beverage', 'agriculture', 'regional_development'], ARRAY['supply_chain', 'logistics', 'food_safety', 'process_automation'], 25, 74, ARRAY['emerging', 'established'], ARRAY['supply_chain', 'gst_registered', 'primary_producer'], 0.4, 0.3, 0.3, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('959d2c36-dc12-4aba-8cf5-27adf9d361c6', 'Carbon Farming and Land Restoration Program', 'carbon-farming-land-restoration', 'DPIRD', 'https://www.dpird.wa.gov.au/carbon-farming-guidelines', 'Grants to support carbon sequestration projects and land restoration activities in Western Australia.', 'Grants for carbon farming and land restoration initiatives across WA.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2024-03-07', '2024-05-20', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'sole_trader', 'partnership', 'trust'], 0, NULL, 0, true, false, ARRAY['regional_wa', 'all_wa'], 'inclusive', ARRAY['agriculture', 'environmental', 'horticulture'], ARRAY['carbon_farming', 'compliance', 'certification'], 0, 74, ARRAY['foundational', 'emerging', 'established'], ARRAY['carbon_farming', 'primary_producer'], 0.5, 0.15, 0.35, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('cb99f60d-4c36-4616-b96b-e82c682f8aae', 'Native Seed and Nursery Development Program Grants', 'native-seed-nursery-development', 'DPIRD', 'https://www.dpird.wa.gov.au/native-seed-guidelines', 'Grants supporting the development of the native seed and nursery sector in Western Australia.', 'Development grants for the WA native seed and nursery industry.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2022-10-28', '2022-12-09', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'sole_trader', 'nfp'], 0, NULL, 0, true, false, ARRAY['all_wa'], 'inclusive', ARRAY['agriculture', 'horticulture', 'environmental'], ARRAY['compliance', 'certification', 'quality_control'], 0, 74, ARRAY['foundational', 'emerging', 'established'], ARRAY['primary_producer'], 0.45, 0.2, 0.35, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('ca378714-1c70-47fa-a5f3-024ce02cb4ac', 'Building Better Aboriginal Businesses Goldfields Grant', 'bbab-goldfields-grant', 'DPIRD', 'https://www.dpird.wa.gov.au/bbab-goldfields-guidelines', 'Grants for Aboriginal-owned businesses in the Goldfields region of Western Australia.', 'Goldfields-specific grants for Aboriginal-owned businesses.', 'monetary_grant', 'funding', 'competitive', 'business', 'closed', '2022-03-04', '2022-04-28', false, 'single_window', NULL, NULL, NULL, NULL, false, ARRAY['company', 'sole_trader', 'partnership'], 0, NULL, 0, true, false, ARRAY['regional_wa'], 'exclusive', ARRAY['indigenous_business', 'regional_development'], ARRAY['brand_development', 'b2b_sales'], 0, 74, ARRAY['foundational', 'emerging', 'established'], ARRAY['indigenous_business_elig'], 0.35, 0.25, 0.4, 'competitive', 'dpird_portal', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', 'Australian Trusted Trader', 'australian-trusted-trader', 'Australian Border Force (ABF)', 'https://www.abf.gov.au/about-us/what-we-do/trustedtrader', 'Free accreditation program for importers, exporters and supply chain service providers with 2+ years in international trade. Provides priority cargo services, dedicated account manager and mutual recognition agreements.', 'Free accreditation for import/export businesses — priority customs services + dedicated account manager.', 'accreditation', 'both', 'non_competitive', 'business', 'ongoing', NULL, NULL, true, 'always_open', 0, 0, 0, 'Free accreditation — no monetary grant', false, ARRAY['company', 'sole_trader', 'partnership', 'trust'], 0, NULL, 2, true, false, ARRAY['all_wa', 'national'], 'inclusive', ARRAY['retail', 'professional_services', 'food_beverage', 'agriculture'], ARRAY['export', 'import', 'supply_chain', 'international_trade', 'compliance'], 50, 100, ARRAY['established', 'advanced'], ARRAY['export', 'import', 'international_trade', 'financially_solvent', 'international_supply_chain'], 0.35, 0.2, 0.45, 'eligibility_only', 'abf_portal', 'trustedtrader@abf.gov.au', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('86fcbc16-6d5e-4b53-a415-26d66ff43d9a', 'First Nations Feature Development', 'first-nations-feature-development', 'Screen Australia', 'https://www.screenaustralia.gov.au/fund/first-nations-feature-development/', 'Development funding for Aboriginal and Torres Strait Islander filmmakers with demonstrated experience to develop feature film screenplays. Writer and director must be First Nations Australians with minimum 3 eligible drama credits.', 'Up to $45K development funding for First Nations filmmakers developing feature film screenplays.', 'monetary_grant', 'funding', 'merit_scored', 'creative_entity', 'open', NULL, '2026-08-20', true, 'rolling_quarterly', 0, 4500000, 0, 'Up to $30K (no producer) or up to $45K (with producer attached)', false, ARRAY['company', 'sole_trader'], 0, NULL, 0, true, false, ARRAY['all_wa', 'national'], 'required', ARRAY['creative_industries'], ARRAY['brand_development', 'digital_marketing'], 0, 100, ARRAY['foundational', 'emerging', 'established', 'advanced'], ARRAY['indigenous_business_elig'], 0.2, 0.3, 0.5, 'merit_scored', 'smartygrants', 'FirstNations@screenaustralia.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('72cd5ba5-fbe8-427d-958d-f4d6bd2d7971', 'Tackle Shop Rebate', 'tackle-shop-rebate', 'DPIRD / ServiceWA', 'https://www.dpird.wa.gov.au/businesses/grants-and-support/TSR/', 'Point-of-purchase rebate of up to $50 for WA recreational fishing licence holders purchasing qualifying fishing gear at participating tackle shops. Part of the Fisheries Support Package.', 'Up to $50 rebate on fishing gear for licensed recreational anglers in WA — claim via ServiceWA App.', 'rebate', 'funding', 'non_competitive', 'individual', 'open', '2026-05-18', '2026-11-17', false, 'single_window', 0, 5000, 0, 'Up to $50 per person on qualifying fishing gear', false, NULL, 0, NULL, 0, false, false, ARRAY['all_wa'], 'inclusive', ARRAY['fishing_recreation'], ARRAY['compliance'], 0, 100, ARRAY['foundational', 'emerging', 'established', 'advanced'], ARRAY['water_license'], 0.5, 0.1, 0.4, 'eligibility_only', 'servicewa_app', 'enquiries@dpird.wa.gov.au', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', 'ASBAS Digital Solutions Round 3', 'asbas-digital-solutions-round-3', 'DISR / Business Grants Hub', 'https://business.gov.au/grants-and-programs/australian-small-business-advisory-services-digital-solutions-round-3', 'Funds service providers to deliver digital advisory services (workshops, mentoring) to small businesses across Australia. 5 priority capabilities: digitalisation, social media/marketing, business software, AI, cybersecurity. Up to 5 hours one-to-one mentoring at $110/session for SMEs.', 'Subsidised digital advisory and training for SMEs (≤19 employees) — 5 hrs mentoring at $110.', 'advisory_subsidy', 'advisory', 'competitive', 'service_provider', 'closed', '2025-10-27', NULL, false, 'annual_competitive', 0, 0, 2513600000, '$110/session for SMEs; service providers compete for area grants up to $8.8M', false, ARRAY['company', 'nfp'], 0, 19, 0, true, true, ARRAY['all_wa', 'national'], 'inclusive', ARRAY['retail', 'food_beverage', 'construction', 'professional_services', 'agriculture'], ARRAY['digital_marketing', 'cybersecurity', 'ai_tools', 'business_software', 'ecommerce'], 0, 49, ARRAY['foundational', 'emerging'], ARRAY['no_digital_presence', 'cybersecurity', 'ai_tools', 'digital_marketing', 'business_software'], 0.1, 0.7, 0.2, 'competitive', 'business_grants_hub', '1300 13 28 46', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO grants (id, name, slug, administering_body, url, description, summary, program_type, support_type, delivery_mode, recipient_type, status, open_date, close_date, is_rolling, deadline_pattern, amount_min, amount_max, total_pool, amount_notes, is_matched_funding, eligible_structures, employee_min, employee_max, business_age_min, requires_abn, requires_gst, geographic_scope, indigenous_focus, sector_tags, objective_tags, dml_min, dml_max, dml_level_tags, trigger_tags, operations_weight, digital_weight, market_weight, assessment_type, application_channel, contact_email, is_featured) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', 'Digital Manufacturing on a Shoestring', 'digital-manufacturing-shoestring', 'DPIRD', 'https://www.dpird.wa.gov.au/businesses/food-and-beverage/food-manufacturing/digital-manufacturing-on-a-shoestring/', 'SME-focused advisory program to help small food manufacturers explore how to apply practical, low-cost digital tools to real business challenges. Targets Food & Beverage manufacturers in Western Australia.', 'Free advisory program helping WA food manufacturers adopt low-cost digital tools.', 'advisory_subsidy', 'advisory', 'non_competitive', 'business', 'ongoing', NULL, NULL, true, 'always_open', 0, 0, 0, 'Free advisory program — no direct monetary grant', false, ARRAY['company', 'sole_trader', 'partnership'], 0, 199, 0, true, false, ARRAY['all_wa'], 'inclusive', ARRAY['food_beverage', 'food_manufacturing'], ARRAY['inventory_software', 'process_automation', 'business_software', 'food_safety', 'digital_marketing'], 0, 49, ARRAY['foundational', 'emerging'], ARRAY['no_digital_presence', 'inventory_software', 'process_automation', 'business_software', 'food_safety'], 0.35, 0.5, 0.15, 'eligibility_only', 'dpird_portal', 'enquiries@dpird.wa.gov.au', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- -----------------------------------------------------------------------------
-- 4. Grant Tags
-- -----------------------------------------------------------------------------
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('6c97d8b8-9aa6-4f91-aba6-2211bed878d7', 'cb572c93-127f-4724-9e68-d83ce75c6ee7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('6c97d8b8-9aa6-4f91-aba6-2211bed878d7', 'fd24f5d3-0918-4a7e-bbc6-7f02fa1240df') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('6c97d8b8-9aa6-4f91-aba6-2211bed878d7', 'eeb81853-523e-4059-af72-593c0ebbae8b') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('6a05fc97-6311-4780-a70f-cb8105c837c1', '9bb0dc5e-1743-46ce-87d9-39a593298b38') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('6a05fc97-6311-4780-a70f-cb8105c837c1', 'cb572c93-127f-4724-9e68-d83ce75c6ee7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('6a05fc97-6311-4780-a70f-cb8105c837c1', '81892e18-cc47-4037-a05d-744e13b40cba') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('78441f34-dd90-4725-9a86-865637cbc119', '056cada1-55e0-44fa-a5f8-133d06d03203') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('78441f34-dd90-4725-9a86-865637cbc119', 'b7286565-75fc-424f-a034-052c82669da8') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('78441f34-dd90-4725-9a86-865637cbc119', '6ca109ea-c861-482d-a8a5-74b00f8581df') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('e1d13b32-aea8-4131-b82e-dcf6e85d67c2', 'e03bc7a4-c40d-486e-b653-957000cc06d5') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('e1d13b32-aea8-4131-b82e-dcf6e85d67c2', '5967a623-bf35-48e8-9973-e6a5a50fcc5d') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('e1d13b32-aea8-4131-b82e-dcf6e85d67c2', '69a36261-3837-4864-88d5-8b9a052d34ea') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('e1d13b32-aea8-4131-b82e-dcf6e85d67c2', 'ca3a1a87-07b7-4341-a46d-4029f08dc362') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('02e54618-cc53-4b38-bdd1-3fb4309faff2', 'd73a91f0-4e47-4718-a4e7-2b9c754825c7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('02e54618-cc53-4b38-bdd1-3fb4309faff2', 'cb572c93-127f-4724-9e68-d83ce75c6ee7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('02e54618-cc53-4b38-bdd1-3fb4309faff2', 'f8b8bce4-107d-4c77-bf13-e6d1cdeb4067') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('8dc3a80b-b148-4689-b8f7-7052c335e3eb', 'd73a91f0-4e47-4718-a4e7-2b9c754825c7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('8dc3a80b-b148-4689-b8f7-7052c335e3eb', 'e03bc7a4-c40d-486e-b653-957000cc06d5') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('8dc3a80b-b148-4689-b8f7-7052c335e3eb', '6ca109ea-c861-482d-a8a5-74b00f8581df') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', '485ca52f-aa46-4225-b55d-220c7ec6fe55') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', 'f2c0a3d5-7598-4e0b-b636-3d03397bfa0e') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', 'ee5cb1d8-501a-4e73-bdf4-60698f8c059e') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', 'e03bc7a4-c40d-486e-b653-957000cc06d5') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', '7fbab832-6e72-494b-9a3a-2904bf7b6b04') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', 'cb9f8a4d-8977-48c7-bd41-b6dc5516c96a') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('86fcbc16-6d5e-4b53-a415-26d66ff43d9a', 'd73a91f0-4e47-4718-a4e7-2b9c754825c7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('86fcbc16-6d5e-4b53-a415-26d66ff43d9a', 'f8b8bce4-107d-4c77-bf13-e6d1cdeb4067') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('72cd5ba5-fbe8-427d-958d-f4d6bd2d7971', 'b7286565-75fc-424f-a034-052c82669da8') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('72cd5ba5-fbe8-427d-958d-f4d6bd2d7971', '81892e18-cc47-4037-a05d-744e13b40cba') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '196269bd-7311-4b52-8a00-21dd76e7c128') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '7174489a-95cd-4591-ba90-f957b1704e96') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '7a786869-8c9e-46c0-95c0-9b15a11f916f') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '29e51eb9-cfa7-4423-8065-8524793cb86b') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '1ac2648a-6cef-4e29-80a2-998d12e065f3') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', 'ba262b11-718f-41fd-8a7e-5f796477e6b7') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', 'eeb81853-523e-4059-af72-593c0ebbae8b') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', '196269bd-7311-4b52-8a00-21dd76e7c128') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', 'd070ad54-d55c-4e47-959a-74159a5817f1') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', 'be2bb8ba-ea21-477f-8ced-085452bdaf08') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', '1ac2648a-6cef-4e29-80a2-998d12e065f3') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', '69a36261-3837-4864-88d5-8b9a052d34ea') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', '1dd94cf4-6aa7-4d8d-b5b8-34b97cc8904b') ON CONFLICT DO NOTHING;
INSERT INTO grant_tags (grant_id, tag_id) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', '8229a90b-1908-43ab-b655-2d9bbf498f88') ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 5. Providers
-- -----------------------------------------------------------------------------
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', 'Digital Solutions Group WA', 'digital-solutions-group-wa', 'Perth-based digital transformation consultancy specialising in SME digital adoption, e-commerce setup, CRM implementation and digital marketing strategy.', 'Digital adoption consulting for WA SMEs — website, e-commerce, CRM, marketing.', 'https://www.digitalsolutionswa.com.au', 'info@digitalsolutionswa.com.au', '+61 8 9XXX XXXX', ARRAY['implementation', 'consulting', 'training'], ARRAY['retail', 'food_beverage', 'professional_services', 'construction'], ARRAY['no_digital_presence', 'website', 'ecommerce', 'crm', 'digital_marketing', 'social_media', 'business_software'], ARRAY['foundational', 'emerging', 'established'], ARRAY['metro_wa', 'regional_wa'], true, 'active', true, '2025-06-01', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('bf323aaa-8fd7-4781-b138-d4ffa878a794', 'AgriDigital WA', 'agridigital-wa', 'Specialist consultancy focused on digital solutions for agricultural and food & beverage businesses in Western Australia. Expertise in IoT, supply chain visibility, food safety compliance systems and inventory management.', 'Digital solutions for WA agriculture and food & beverage — IoT, supply chain, compliance.', 'https://www.agridigitalwa.com.au', 'info@agridigitalwa.com.au', '+61 8 9XXX XXXX', ARRAY['implementation', 'consulting'], ARRAY['agriculture', 'food_beverage', 'food_manufacturing', 'horticulture', 'aquaculture'], ARRAY['inventory_software', 'supply_chain', 'food_safety', 'process_automation', 'compliance', 'certification', 'water_management'], ARRAY['foundational', 'emerging', 'established'], ARRAY['metro_wa', 'regional_wa'], true, 'active', true, '2025-03-15', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('435d2deb-1a89-4261-87ab-767ce5e38e3b', 'Indigenous Business Solutions WA', 'indigenous-business-solutions-wa', 'Aboriginal-owned consulting firm providing business development, digital advisory and capacity building services specifically for Indigenous businesses across Western Australia.', 'Business development and digital advisory for Indigenous businesses across WA.', 'https://www.ibswa.com.au', 'info@ibswa.com.au', '+61 8 9XXX XXXX', ARRAY['consulting', 'training'], ARRAY['indigenous_business', 'regional_development'], ARRAY['brand_development', 'b2b_sales', 'digital_marketing', 'business_software', 'compliance'], ARRAY['foundational', 'emerging', 'established'], ARRAY['metro_wa', 'regional_wa'], true, 'active', true, '2025-07-01', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', 'WA Export Advisory Services', 'wa-export-advisory-services', 'Specialists in international trade strategy, export market development and supply chain compliance for WA exporters. Supports businesses seeking Australian Trusted Trader accreditation.', 'Export strategy, market development and ATT accreditation support for WA businesses.', 'https://www.waexportadvisory.com.au', 'info@waexportadvisory.com.au', '+61 8 9XXX XXXX', ARRAY['consulting', 'advisory'], ARRAY['agriculture', 'food_beverage', 'retail', 'professional_services'], ARRAY['export', 'import', 'international_trade', 'supply_chain', 'compliance', 'certification', 'financially_solvent', 'international_supply_chain'], ARRAY['established', 'advanced'], ARRAY['metro_wa'], true, 'active', true, '2025-09-01', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('f22a7ac9-1dd1-47e3-a74a-c9abb97bb041', 'CyberSecure WA', 'cybersecure-wa', 'Cybersecurity advisory firm providing risk assessments, staff training, security audits and implementation support for WA small businesses. ASBAS Digital Solutions approved provider.', 'Cybersecurity risk assessment, training and implementation for WA small businesses.', 'https://www.cybersecurewa.com.au', 'info@cybersecurewa.com.au', '+61 8 9XXX XXXX', ARRAY['consulting', 'training', 'audit'], ARRAY['retail', 'professional_services', 'food_beverage', 'construction'], ARRAY['cybersecurity', 'cloud_services', 'compliance', 'business_software'], ARRAY['foundational', 'emerging', 'established'], ARRAY['metro_wa', 'regional_wa'], true, 'active', true, '2025-04-20', false) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', 'FoodTech WA', 'foodtech-wa', 'Technology consultancy focused exclusively on the food and beverage manufacturing sector. Specialises in Digital Shoestring implementations, production management software, HACCP digital compliance and lean manufacturing digitalisation.', 'Digital transformation for WA food & beverage manufacturers — Shoestring approach.', 'https://www.foodtechwa.com.au', 'info@foodtechwa.com.au', '+61 8 9XXX XXXX', ARRAY['implementation', 'consulting', 'training'], ARRAY['food_beverage', 'food_manufacturing'], ARRAY['inventory_software', 'process_automation', 'food_safety', 'business_software', 'no_digital_presence', 'quality_control'], ARRAY['foundational', 'emerging'], ARRAY['metro_wa', 'regional_wa'], true, 'active', true, '2025-11-01', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO providers (id, name, slug, description, summary, website, email, phone, service_types, sector_tags, trigger_tags, dml_levels, location, operates_online, status, dpird_approved, approval_date, is_featured) VALUES ('679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', 'Small Business Development Corporation (SBDC)', 'sbdc-wa', 'WA Government agency providing free and low-cost business advisory, training and mentoring services to small businesses across Western Australia. Delivers ASBAS Digital Solutions program.', 'Free business advisory and digital training for WA small businesses — government backed.', 'https://www.smallbusiness.wa.gov.au', 'advice@sbdc.wa.gov.au', '1800 199 125', ARRAY['consulting', 'training', 'advisory'], ARRAY['retail', 'food_beverage', 'construction', 'professional_services', 'agriculture', 'regional_development'], ARRAY['no_digital_presence', 'business_software', 'digital_marketing', 'ecommerce', 'social_media', 'cybersecurity'], ARRAY['foundational', 'emerging', 'established'], ARRAY['metro_wa', 'regional_wa'], true, 'active', true, '2024-01-01', true) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

-- -----------------------------------------------------------------------------
-- 6. Provider Tags
-- -----------------------------------------------------------------------------
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', '375150a6-354f-4672-83cb-d889fb981aeb') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', 'ba262b11-718f-41fd-8a7e-5f796477e6b7') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', '32a1dbd9-19a8-4b56-abb5-2b7201c23053') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', '29e51eb9-cfa7-4423-8065-8524793cb86b') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', '8d332fb9-c25c-4c13-8f81-609a33c274ec') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('4955acc6-2670-4e7b-87e6-06dc95e1853b', '196269bd-7311-4b52-8a00-21dd76e7c128') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('bf323aaa-8fd7-4781-b138-d4ffa878a794', 'd070ad54-d55c-4e47-959a-74159a5817f1') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('bf323aaa-8fd7-4781-b138-d4ffa878a794', 'e03bc7a4-c40d-486e-b653-957000cc06d5') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('bf323aaa-8fd7-4781-b138-d4ffa878a794', '69a36261-3837-4864-88d5-8b9a052d34ea') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('bf323aaa-8fd7-4781-b138-d4ffa878a794', 'be2bb8ba-ea21-477f-8ced-085452bdaf08') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('bf323aaa-8fd7-4781-b138-d4ffa878a794', '056cada1-55e0-44fa-a5f8-133d06d03203') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('435d2deb-1a89-4261-87ab-767ce5e38e3b', 'd73a91f0-4e47-4718-a4e7-2b9c754825c7') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('435d2deb-1a89-4261-87ab-767ce5e38e3b', 'f8b8bce4-107d-4c77-bf13-e6d1cdeb4067') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('435d2deb-1a89-4261-87ab-767ce5e38e3b', 'eeca24b1-1f45-488c-a644-01779acf7ee3') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', '485ca52f-aa46-4225-b55d-220c7ec6fe55') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', 'f2c0a3d5-7598-4e0b-b636-3d03397bfa0e') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', 'ee5cb1d8-501a-4e73-bdf4-60698f8c059e') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', 'cb9f8a4d-8977-48c7-bd41-b6dc5516c96a') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('f22a7ac9-1dd1-47e3-a74a-c9abb97bb041', '7174489a-95cd-4591-ba90-f957b1704e96') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('f22a7ac9-1dd1-47e3-a74a-c9abb97bb041', 'fced5da6-dc31-4fc8-ae0a-f7c9f463f706') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('f22a7ac9-1dd1-47e3-a74a-c9abb97bb041', '81892e18-cc47-4037-a05d-744e13b40cba') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', 'd070ad54-d55c-4e47-959a-74159a5817f1') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', 'be2bb8ba-ea21-477f-8ced-085452bdaf08') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', '69a36261-3837-4864-88d5-8b9a052d34ea') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', '196269bd-7311-4b52-8a00-21dd76e7c128') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', '196269bd-7311-4b52-8a00-21dd76e7c128') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', '1ac2648a-6cef-4e29-80a2-998d12e065f3') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', '29e51eb9-cfa7-4423-8065-8524793cb86b') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', 'ba262b11-718f-41fd-8a7e-5f796477e6b7') ON CONFLICT DO NOTHING;
INSERT INTO provider_tags (provider_id, tag_id) VALUES ('679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', '7174489a-95cd-4591-ba90-f957b1704e96') ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 7. Grant Providers
-- -----------------------------------------------------------------------------
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', 'cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', 'Primary implementation partner for the Digital Shoestring program.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', 'bf323aaa-8fd7-4781-b138-d4ffa878a794', 'Supply chain and inventory digital solutions for food manufacturers.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('559c16fa-8898-4be0-bc2b-798951aabe4a', '679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', 'Business advisory and ASBAS training complement to the program.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '679e3b5b-75a8-47c0-b9f7-6ea40b9409ae', 'Approved ASBAS service delivery organisation for WA.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', 'f22a7ac9-1dd1-47e3-a74a-c9abb97bb041', 'Delivers cybersecurity advisory sessions under ASBAS.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', '4955acc6-2670-4e7b-87e6-06dc95e1853b', 'Delivers digital adoption and marketing sessions under ASBAS.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('cbf1c474-5b02-4b94-a578-668c3b856aad', '20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', 'Provides ATT application support and international trade consulting.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('e1d13b32-aea8-4131-b82e-dcf6e85d67c2', 'bf323aaa-8fd7-4781-b138-d4ffa878a794', 'Supports digital supply chain optimisation for food & beverage grantees.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('02e54618-cc53-4b38-bdd1-3fb4309faff2', '435d2deb-1a89-4261-87ab-767ce5e38e3b', 'Business development advisory for Noongar corporations.') ON CONFLICT DO NOTHING;
INSERT INTO grant_providers (grant_id, provider_id, notes) VALUES ('8dc3a80b-b148-4689-b8f7-7052c335e3eb', '435d2deb-1a89-4261-87ab-767ce5e38e3b', 'Advisory support for Aboriginal businesses accessing the voucher.') ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 8. Questions
-- -----------------------------------------------------------------------------
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('8c460c41-00fb-4f07-9ddb-5c64dd25333d', 'What is the primary industry sector of your business?', 'Select the category that best describes your main business activity.', 'profile', 1, 'single_choice', '{"summary": "Agriculture | Food & Beverage | Retail & Wholesale | Construction | Professional Services | Aquaculture | Horticulture | Environmental | Indigenous Business | Creative Industries | Other"}'::jsonb, NULL, NULL, true, true, 1) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('84f1d361-3927-4dec-b317-9aba91c8c7ed', 'How many people does your business currently employ?', 'Include full-time, part-time and casual employees.', 'profile', 1, 'single_choice', '{"summary": "1–4 (micro) | 5–19 (small) | 20–49 (small-medium) | 50–199 (medium) | 200+ (large)"}'::jsonb, NULL, NULL, true, true, 2) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('f9c27b76-b29f-4e8b-be9b-28d28993f925', 'How long has your business been operating?', 'Count from the date of your ABN registration or trading commencement.', 'profile', 1, 'single_choice', '{"summary": "Less than 12 months | 1–2 years | 2–5 years | More than 5 years"}'::jsonb, NULL, NULL, true, true, 3) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('c3802e03-e6cc-4055-af04-39f90648d755', 'What is your approximate annual turnover?', 'Use your most recent full financial year.', 'profile', 1, 'single_choice', '{"summary": "Under $75,000 | $75K–$250K | $250K–$1M | $1M–$5M | More than $5M"}'::jsonb, NULL, NULL, true, true, 4) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('9b48b99d-4fbf-4f9c-938f-dd39bf2d5835', 'What is your business structure?', NULL, 'profile', 1, 'single_choice', '{"summary": "Sole trader | Partnership | Company (Pty Ltd) | Trust | Not-for-profit | Indigenous Corporation"}'::jsonb, NULL, NULL, true, true, 5) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('cdc29374-76d4-4618-88b8-1225aa236fff', 'Where is your business primarily located?', NULL, 'profile', 1, 'single_choice', '{"summary": "Perth Metro (within 50km of CBD) | Regional WA | Remote WA"}'::jsonb, NULL, NULL, true, true, 6) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('7f6a9b44-76b5-4353-96c7-eff223ec6a4f', 'Is your business Aboriginal or Torres Strait Islander owned (50%+ ownership)?', 'This helps us identify programs with Indigenous eligibility requirements.', 'profile', 1, 'boolean', '{"summary": "Yes | No"}'::jsonb, NULL, NULL, true, true, 7) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('f65fb95d-35c5-488d-bd1e-1907e3d52be5', 'Does your business have a website?', 'Count any web presence where customers can find information about your business.', 'digital', 1.5, 'single_choice', '{"summary": "No website (score: 0) | Basic informational site (score: 25) | Active website with contact/booking (score: 50) | Full e-commerce website (score: 100)"}'::jsonb, NULL, NULL, true, true, 10) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('8459eb2b-61b6-4b1d-9700-494a7d7cf762', 'How does your business use social media?', 'Consider Facebook, Instagram, LinkedIn or any other platform.', 'digital', 1, 'single_choice', '{"summary": "No social media presence (score: 0) | Personal profiles only (score: 10) | Business page, occasional posts (score: 30) | Regular posting and community engagement (score: 70) | Paid ads and analytics (score: 100)"}'::jsonb, NULL, NULL, true, true, 11) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('74156ce6-3521-4393-aa35-af16ab883731', 'How do you manage your customer relationships and contact information?', NULL, 'digital', 1.2, 'single_choice', '{"summary": "Pen and paper or memory (score: 0) | Spreadsheet/Excel (score: 20) | Email platform only (score: 40) | Dedicated CRM software (score: 80) | CRM integrated with sales pipeline (score: 100)"}'::jsonb, NULL, NULL, true, true, 12) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('c5de7ea5-019c-4931-9aaa-293a1ef725a7', 'How do you manage stock and inventory?', 'Skip if your business does not hold physical stock.', 'digital', 1, 'single_choice', '{"summary": "Manual counting / spreadsheet (score: 0) | Basic accounting software (score: 30) | Dedicated inventory software (score: 70) | Automated real-time inventory system (score: 100)"}'::jsonb, ARRAY['agriculture', 'food_beverage', 'food_manufacturing', 'retail', 'aquaculture', 'horticulture'], NULL, true, true, 13) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('0ab6a501-e96a-41b0-bac2-c9b1844eb887', 'How do you process sales and payments?', NULL, 'digital', 1, 'single_choice', '{"summary": "Cash only (score: 0) | Basic EFTPOS only (score: 20) | POS system with sales reporting (score: 60) | Integrated POS + online + accounting (score: 100)"}'::jsonb, ARRAY['retail', 'food_beverage'], NULL, true, true, 14) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('cc25ccae-7814-46c5-8cc7-a914d3b804c1', 'Does your business use cloud-based software or services?', 'Examples: Microsoft 365, Google Workspace, Xero, MYOB, Dropbox.', 'digital', 1, 'single_choice', '{"summary": "No cloud software at all (score: 0) | 1 cloud tool (score: 25) | 2–3 cloud tools (score: 60) | 4+ cloud tools integrated (score: 100)"}'::jsonb, NULL, NULL, true, true, 15) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('b395c272-8c05-4554-9a29-2f585971967a', 'How does your business manage cybersecurity and data protection?', NULL, 'digital', 1, 'single_choice', '{"summary": "No formal measures in place (score: 0) | Basic antivirus only (score: 15) | Password policies + antivirus (score: 40) | Multi-factor authentication + regular backups (score: 70) | Formal security policy + staff training + incident plan (score: 100)"}'::jsonb, NULL, NULL, true, true, 16) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('d3521b15-e622-4979-8048-adea1d85e795', 'Does your business currently use or plan to adopt Artificial Intelligence tools?', 'Examples: ChatGPT, AI image tools, predictive analytics, automated chatbots.', 'digital', 0.8, 'single_choice', '{"summary": "No awareness or interest (score: 0) | Aware but not using (score: 10) | Using basic AI tools occasionally (score: 40) | AI integrated into regular operations (score: 80) | AI drives key business decisions (score: 100)"}'::jsonb, NULL, NULL, false, true, 17) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('df1a93d0-5754-4965-86de-1ebbd99f6aa8', 'Do you have documented processes for your key business operations?', 'Written SOPs, checklists or guides that staff can follow.', 'operations', 1.2, 'single_choice', '{"summary": "No documentation — all in owner''s head (score: 0) | Some informal notes (score: 20) | Key processes partially documented (score: 50) | All main processes documented and followed (score: 80) | Full quality management system (score: 100)"}'::jsonb, NULL, NULL, true, true, 20) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('8ce85767-13c4-4c33-b482-9f14e9999ae6', 'How visible and manageable is your supply chain?', 'Skip if your business does not rely on a supply chain.', 'operations', 1, 'single_choice', '{"summary": "No visibility — reactive management (score: 0) | Basic supplier list (score: 20) | Regular supplier communication + lead times tracked (score: 50) | Digital supply chain tracking (score: 80) | Fully integrated supply chain data (score: 100)"}'::jsonb, ARRAY['agriculture', 'food_beverage', 'food_manufacturing', 'retail', 'construction'], NULL, false, true, 21) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('c637e1cb-5920-4e26-957f-818d98a85a58', 'How does your business manage product or service quality?', NULL, 'operations', 1, 'single_choice', '{"summary": "No formal quality checks (score: 0) | Informal spot checks (score: 20) | Regular quality reviews (score: 50) | Documented QC procedures (score: 75) | Certified quality management system (score: 100)"}'::jsonb, NULL, NULL, true, true, 22) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('ede1c8e5-c22c-4ec0-94d8-67f071405d4c', 'How does your business manage regulatory compliance?', 'Consider food safety, environmental, workplace safety and sector-specific regulations.', 'operations', 1, 'single_choice', '{"summary": "Limited awareness of requirements (score: 0) | Know requirements, manage manually (score: 30) | All requirements met, some documentation (score: 60) | Fully documented and audited compliance (score: 100)"}'::jsonb, NULL, NULL, true, true, 23) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('c9c149ec-3602-4a71-b346-aafe62b40294', 'Which repetitive operational tasks have you automated or digitised?', 'Select all that apply.', 'operations', 0.8, 'multi_choice', '{"summary": "None automated | Invoicing/accounting | Payroll | Staff scheduling | Customer communications | Production/manufacturing | Reporting and analytics"}'::jsonb, NULL, NULL, false, true, 24) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('bb1475ca-3764-4c4b-a36e-4566667de2c4', 'Does your business currently sell products or services online?', NULL, 'market', 1.2, 'single_choice', '{"summary": "No online sales (score: 0) | Third-party marketplace only (eBay, Amazon) (score: 25) | Own website with online sales (score: 60) | Multiple online channels integrated (score: 100)"}'::jsonb, NULL, NULL, true, true, 30) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('599ae490-841a-4927-b443-da05cf3b5b02', 'Does your business export products or services internationally?', NULL, 'market', 1, 'single_choice', '{"summary": "No — domestic only (score: 0) | Exploring export opportunities (score: 10) | Occasional/ad-hoc exports (score: 40) | Regular export program (score: 70) | Established international markets (score: 100)"}'::jsonb, NULL, NULL, true, true, 31) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('eb6625cf-8f57-472b-8c7d-8068e9d1fc01', 'What is your primary method of acquiring new customers?', 'Select the most important channel for your business.', 'market', 1, 'single_choice', '{"summary": "Word of mouth only | Print/radio/TV advertising | Own website/SEO | Social media | Online ads (Google/Facebook) | Trade shows and events | Government/business directories | Other digital channels"}'::jsonb, NULL, NULL, true, true, 32) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('1b94b688-a742-4471-a095-924d3f5e45e2', 'Do you have a documented digital marketing strategy?', 'A written plan for how you attract and retain customers online.', 'market', 1, 'single_choice', '{"summary": "No strategy (score: 0) | Informal approach (score: 15) | Basic written plan (score: 40) | Documented strategy with KPIs (score: 75) | Full digital marketing strategy with regular review (score: 100)"}'::jsonb, NULL, NULL, true, true, 33) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;
INSERT INTO questions (id, text, helper_text, dimension, dimension_weight, answer_type, options, sector_filter, show_if, is_required, is_active, sort_order) VALUES ('64766194-48dc-4616-8512-8cb007bc6308', 'How would you describe your brand''s digital presence?', 'Consider website, social media, online reviews and search visibility.', 'market', 0.8, 'single_choice', '{"summary": "No recognisable digital presence (score: 0) | Basic presence, inconsistent (score: 20) | Consistent branding across channels (score: 50) | Strong digital brand with active engagement (score: 80) | Market-leading digital brand (score: 100)"}'::jsonb, NULL, NULL, true, true, 34) ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;

-- -----------------------------------------------------------------------------
-- 9. Question Tags
-- -----------------------------------------------------------------------------
INSERT INTO question_tags (question_id, tag_id) VALUES ('f65fb95d-35c5-488d-bd1e-1907e3d52be5', '375150a6-354f-4672-83cb-d889fb981aeb') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('f65fb95d-35c5-488d-bd1e-1907e3d52be5', '196269bd-7311-4b52-8a00-21dd76e7c128') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('f65fb95d-35c5-488d-bd1e-1907e3d52be5', 'ba262b11-718f-41fd-8a7e-5f796477e6b7') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('8459eb2b-61b6-4b1d-9700-494a7d7cf762', '8d332fb9-c25c-4c13-8f81-609a33c274ec') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('8459eb2b-61b6-4b1d-9700-494a7d7cf762', '29e51eb9-cfa7-4423-8065-8524793cb86b') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('74156ce6-3521-4393-aa35-af16ab883731', '32a1dbd9-19a8-4b56-abb5-2b7201c23053') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('c5de7ea5-019c-4931-9aaa-293a1ef725a7', 'd070ad54-d55c-4e47-959a-74159a5817f1') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('0ab6a501-e96a-41b0-bac2-c9b1844eb887', 'ab9e2ddc-2f73-423e-a651-877c2543875d') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('cc25ccae-7814-46c5-8cc7-a914d3b804c1', 'fced5da6-dc31-4fc8-ae0a-f7c9f463f706') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('cc25ccae-7814-46c5-8cc7-a914d3b804c1', '1ac2648a-6cef-4e29-80a2-998d12e065f3') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('b395c272-8c05-4554-9a29-2f585971967a', '7174489a-95cd-4591-ba90-f957b1704e96') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('d3521b15-e622-4979-8048-adea1d85e795', '7a786869-8c9e-46c0-95c0-9b15a11f916f') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('df1a93d0-5754-4965-86de-1ebbd99f6aa8', 'be2bb8ba-ea21-477f-8ced-085452bdaf08') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('df1a93d0-5754-4965-86de-1ebbd99f6aa8', '4df73018-979d-4147-99c5-7ee04d9ec55c') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('8ce85767-13c4-4c33-b482-9f14e9999ae6', 'e03bc7a4-c40d-486e-b653-957000cc06d5') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('8ce85767-13c4-4c33-b482-9f14e9999ae6', '5967a623-bf35-48e8-9973-e6a5a50fcc5d') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('c637e1cb-5920-4e26-957f-818d98a85a58', '4df73018-979d-4147-99c5-7ee04d9ec55c') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('c637e1cb-5920-4e26-957f-818d98a85a58', '6a7b1107-e612-4104-b14e-a6361c7f97ab') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('ede1c8e5-c22c-4ec0-94d8-67f071405d4c', '81892e18-cc47-4037-a05d-744e13b40cba') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('ede1c8e5-c22c-4ec0-94d8-67f071405d4c', '69a36261-3837-4864-88d5-8b9a052d34ea') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('bb1475ca-3764-4c4b-a36e-4566667de2c4', 'ba262b11-718f-41fd-8a7e-5f796477e6b7') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('bb1475ca-3764-4c4b-a36e-4566667de2c4', '29e51eb9-cfa7-4423-8065-8524793cb86b') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('599ae490-841a-4927-b443-da05cf3b5b02', '485ca52f-aa46-4225-b55d-220c7ec6fe55') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('599ae490-841a-4927-b443-da05cf3b5b02', 'ee5cb1d8-501a-4e73-bdf4-60698f8c059e') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('1b94b688-a742-4471-a095-924d3f5e45e2', '2a8324bf-d7d5-459a-9e86-97047eda7821') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('64766194-48dc-4616-8512-8cb007bc6308', 'f8b8bce4-107d-4c77-bf13-e6d1cdeb4067') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('7f6a9b44-76b5-4353-96c7-eff223ec6a4f', 'd73a91f0-4e47-4718-a4e7-2b9c754825c7') ON CONFLICT DO NOTHING;
INSERT INTO question_tags (question_id, tag_id) VALUES ('7f6a9b44-76b5-4353-96c7-eff223ec6a4f', 'cde69925-71af-452f-b325-7faca1ee2259') ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- 10. Consultants
-- -----------------------------------------------------------------------------
INSERT INTO consultants (id, name, email, role, region, is_active) VALUES ('4c378b9c-8785-47ea-8dc7-fba9fb066c67', 'Sarah Mitchell', 's.mitchell@dpird.wa.gov.au', 'admin', 'All WA', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO consultants (id, name, email, role, region, is_active) VALUES ('863a1c4b-1999-4f3c-bb89-3fe37b2433c8', 'James Nguyen', 'j.nguyen@dpird.wa.gov.au', 'advisor', 'Perth Metro', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO consultants (id, name, email, role, region, is_active) VALUES ('99902b05-02dc-44cc-b563-7e74504007a4', 'Priya Sharma', 'p.sharma@dpird.wa.gov.au', 'advisor', 'South West WA', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO consultants (id, name, email, role, region, is_active) VALUES ('f79bcff0-510d-4040-8710-0c27b32cbf07', 'Tom Watkins', 't.watkins@dpird.wa.gov.au', 'advisor', 'Wheatbelt & Goldfields', true) ON CONFLICT (email) DO NOTHING;
INSERT INTO consultants (id, name, email, role, region, is_active) VALUES ('e4358404-8482-4863-b264-f223203b3917', 'Leanne Cooper', 'l.cooper@dpird.wa.gov.au', 'manager', 'All WA', true) ON CONFLICT (email) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 11. Diagnostic Sessions
-- -----------------------------------------------------------------------------
INSERT INTO diagnostic_sessions (id, session_mode, business_name, contact_name, contact_email, sector_id, business_structure, employee_count, annual_turnover_range, business_age_years, location, has_abn, is_indigenous, operations_score, digital_score, market_score, total_score, dml_level, activated_tags, status, completed_at) VALUES ('f1b20b02-dcc2-4286-80eb-a465c4bea165', 'self_service', 'Sunshine Bakery Perth', 'Maria Santos', 'maria@sunshinebakery.com.au', '23a46d98-921f-4803-9ffd-5e490145e65b', 'sole_trader', 4, '$75K–$250K', 3, 'metro_wa', true, false, 35, 18, 22, 24.9, 'foundational', ARRAY['no_digital_presence', 'food_safety', 'foundational', 'regional_market'], 'completed', '2026-08-10 14:32:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO diagnostic_sessions (id, session_mode, business_name, contact_name, contact_email, sector_id, business_structure, employee_count, annual_turnover_range, business_age_years, location, has_abn, is_indigenous, operations_score, digital_score, market_score, total_score, dml_level, activated_tags, status, completed_at) VALUES ('69fe044b-20ae-4dac-9924-ce5043ec65f0', 'consultant_guided', 'Greenfields Organics WA', 'David Kowalski', 'david@greenfieldswa.com.au', '32b9a7fb-6042-428b-b761-415b709e0ea0', 'company', 22, '$1M–$5M', 8, 'regional_wa', true, false, 62, 48, 55, 53.3, 'established', ARRAY['website', 'social_media', 'supply_chain', 'export', 'established', 'certification'], 'completed', '2026-08-12 10:15:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO diagnostic_sessions (id, session_mode, business_name, contact_name, contact_email, sector_id, business_structure, employee_count, annual_turnover_range, business_age_years, location, has_abn, is_indigenous, operations_score, digital_score, market_score, total_score, dml_level, activated_tags, status, completed_at) VALUES ('5c799aac-8dce-4fd5-a402-e3e803bb7e94', 'self_service', 'Kimberley Indigenous Crafts', 'Aunty Rose Djanbi', 'rose@kimberleycrafts.com.au', '9dc6c815-0ee4-4bf0-83f4-1ac0e7d0e963', 'sole_trader', 2, '$75K–$250K', 5, 'regional_wa', true, true, 28, 15, 30, 22.95, 'foundational', ARRAY['indigenous_business_elig', 'no_digital_presence', 'brand_development', 'foundational', 'indigenous_market'], 'completed', '2026-08-13 16:45:00') ON CONFLICT (id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 12. User Responses
-- -----------------------------------------------------------------------------
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('cb27f723-ea3d-4ba6-8c71-fc987c0787a7', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', '8c460c41-00fb-4f07-9ddb-5c64dd25333d', 'food_beverage', ARRAY['food_safety'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('010929fc-2318-497b-bca9-8528848d2a90', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', '84f1d361-3927-4dec-b317-9aba91c8c7ed', '1–4 (micro)', NULL, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('69eb2e50-bcc3-4162-9f31-ae8b16b701ad', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'f65fb95d-35c5-488d-bd1e-1907e3d52be5', 'No website', ARRAY['no_digital_presence', 'foundational'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('3f5d2612-ffe9-4df7-acf3-b374271b1cd1', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', '8459eb2b-61b6-4b1d-9700-494a7d7cf762', 'Business page, occasional posts', ARRAY['social_media'], 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('273b7b26-de4e-4ef5-8ef8-4a8d2d3edf00', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'b395c272-8c05-4554-9a29-2f585971967a', 'No formal measures', ARRAY['cybersecurity'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('7c12d6ee-ad89-49d9-bd03-e72f3e601176', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'df1a93d0-5754-4965-86de-1ebbd99f6aa8', 'Some informal notes', NULL, 20) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('a1aa1a63-48dd-4ac3-89a8-243e391861b7', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'bb1475ca-3764-4c4b-a36e-4566667de2c4', 'No online sales', NULL, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('300e8a1a-35b8-4500-9318-b913a98c131f', '69fe044b-20ae-4dac-9924-ce5043ec65f0', '8c460c41-00fb-4f07-9ddb-5c64dd25333d', 'horticulture', ARRAY['supply_chain', 'certification'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('e4ef7125-9137-499e-8f07-020860d0cd83', '69fe044b-20ae-4dac-9924-ce5043ec65f0', 'f65fb95d-35c5-488d-bd1e-1907e3d52be5', 'Active website with contact/booking', ARRAY['website'], 50) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('33598fe2-d05a-4a4e-8c5a-8cee148aba02', '69fe044b-20ae-4dac-9924-ce5043ec65f0', '599ae490-841a-4927-b443-da05cf3b5b02', 'Regular export program', ARRAY['export', 'international_trade'], 70) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('6b92ce19-ca67-4532-817d-f3d0282573d9', '5c799aac-8dce-4fd5-a402-e3e803bb7e94', '8c460c41-00fb-4f07-9ddb-5c64dd25333d', 'indigenous_business', ARRAY['indigenous_business_elig'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('cf8f8744-7a4f-4b77-b8eb-1fd3b6e2fb25', '5c799aac-8dce-4fd5-a402-e3e803bb7e94', 'f65fb95d-35c5-488d-bd1e-1907e3d52be5', 'No website', ARRAY['no_digital_presence', 'foundational'], 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO user_responses (id, session_id, question_id, answer_value, tags_activated, score_contribution) VALUES ('23ba0982-df43-4a1b-a185-5836d2db1379', '5c799aac-8dce-4fd5-a402-e3e803bb7e94', '7f6a9b44-76b5-4353-96c7-eff223ec6a4f', 'Yes', ARRAY['indigenous_business_elig', 'indigenous_market'], 0) ON CONFLICT (id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 13. Match Results
-- -----------------------------------------------------------------------------
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('9a504a42-2aff-4506-84da-f8680e161fb3', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'grant', '559c16fa-8898-4be0-bc2b-798951aabe4a', NULL, 0.94, 1, ARRAY['no_digital_presence', 'food_safety', 'foundational', 'food_beverage'], true, '{"summary": "Food & Beverage sector at Foundational DML — exactly the target profile. Program offers free advisory for SME food manufacturers."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('6fc810cd-542f-4b16-a9a0-2d88c9957a00', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'grant', '5dcd6acd-9891-4fef-88c6-e9d7ab46b44c', NULL, 0.82, 2, ARRAY['no_digital_presence', 'cybersecurity', 'business_software', 'foundational'], true, '{"summary": "≤19 employees, no digital presence detected. ASBAS provides subsidised digital advisory at $110/session."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('3e5481a0-8591-40ac-8d33-a1c90dfb1129', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'provider', NULL, 'cb82fe6a-b4dc-4cf7-830d-c8d4e0703313', 0.91, 1, ARRAY['no_digital_presence', 'food_safety', 'inventory_software', 'foundational'], true, '{"summary": "Specialist food & beverage digital provider aligned with Digital Shoestring program."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('cb306625-fdc0-4e14-a1d9-d37f33b83e47', 'f1b20b02-dcc2-4286-80eb-a465c4bea165', 'provider', NULL, NULL, 0.85, 2, ARRAY['no_digital_presence', 'business_software', 'digital_marketing'], true, '{"summary": "Free government-backed advisory — ideal entry point for a foundational SME."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('03da825c-a0d7-4be9-b3d0-088a70702498', '69fe044b-20ae-4dac-9924-ce5043ec65f0', 'grant', 'cbf1c474-5b02-4b94-a578-668c3b856aad', NULL, 0.88, 1, ARRAY['export', 'international_trade', 'supply_chain', 'established'], true, '{"summary": "Active exporter with 8 years trading. Meets 2-year supply chain requirement. ATT accreditation unlocks priority customs clearance."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('a00ac365-fcba-45e8-8138-9e16c84399ed', '69fe044b-20ae-4dac-9924-ce5043ec65f0', 'provider', NULL, '20bcd5bf-27c6-4a6b-b08b-2b3ef785d481', 0.92, 1, ARRAY['export', 'international_trade', 'international_supply_chain', 'certification'], true, '{"summary": "Direct match on export + international trade tags. Can support ATT application process."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('38fc28ec-5ab1-49a6-80d1-b38e2634c9ae', '5c799aac-8dce-4fd5-a402-e3e803bb7e94', 'grant', '02e54618-cc53-4b38-bdd1-3fb4309faff2', NULL, 0.45, 1, ARRAY['indigenous_business_elig'], false, '{"summary": "INELIGIBLE — only for the 6 Noongar Regional Corporations under SWNT Settlement. Does not apply to Kimberley businesses."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('cfb33bef-e2c2-4527-991b-543fa24c9cff', '5c799aac-8dce-4fd5-a402-e3e803bb7e94', 'grant', '8dc3a80b-b148-4689-b8f7-7052c335e3eb', NULL, 0.78, 2, ARRAY['indigenous_business_elig', 'brand_development'], true, '{"summary": "Aboriginal-owned business with 5 years trading (>12 months required). Voucher supports supply chain development."}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO match_results (id, session_id, result_type, grant_id, provider_id, match_score, match_rank, matched_tags, eligibility_met, reasoning_path) VALUES ('33cd3063-70a1-41bd-afc1-ca66c9e0729b', '5c799aac-8dce-4fd5-a402-e3e803bb7e94', 'provider', NULL, '435d2deb-1a89-4261-87ab-767ce5e38e3b', 0.95, 1, ARRAY['indigenous_business_elig', 'brand_development', 'b2b_sales', 'no_digital_presence'], true, '{"summary": "Aboriginal-owned consultancy specialising in Indigenous businesses — perfect fit for digital advisory and business development."}'::jsonb) ON CONFLICT (id) DO NOTHING;